### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by Jerry-py**
## Description

Refactoring code and optimize imgs

## Checklist

- [] - All code changes have been tested, if any
- [] - The documentation has been updated accordingly for any code changes
- [] - This PR fixes an already existing issue
- [] - This PR adds a new feature (new functions, methods, classes, parameters, etc.)
- [] - This PR fixes a bug
- [x] - This PR changes the main DShell cog
- [] - This PR is a breaking change (removes/renames functions, parameters etc.)
- [] - This PR is NOT a code change (changes Documentation files, README.md, CONTRIBUTING.md etc.)

### CODE REVIEW

**Comment by Jerry-py** [comment]
Will test later

**Comment by ImNimboss** [comment]
Looks great to me, I'll test it from my side too. If all goes well, I'll merge it

**Comment by Jerry-py** [comment]
OK cool

**Comment by ImNimboss** [comment]
Tested it, it works. Thanks for contributing :>

**Comment by Jerry-py** [comment]
Np

**Pull request merged**
